name = "przeprogramowani-site"
compatibility_date = "2026-07-31"

# Cloudflare Pages reads this value when deploying with Wrangler.
pages_build_output_dir = "./dist"

# For Cloudflare Pages, use `npm run build` and set the output directory to `dist`.
